version: '2.4'

services:
  postgres:
    image: postgres:11
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hatchways
      POSTGRES_PASSWORD: hatchways
      POSTGRES_DB: messenger
  redis:
    image: redis
    command: redis-server --requirepass hatchways
    ports:
      - '6379:6379'
